### ISSUE TITLE
2.0-rc2 android: Ubable to guarantee application will handle configuration change..

### ISSUE THREAD

**Issue by kles4enko** [playn/playn#16]
After switching to rc2 always see this error. But requested `android:configChanges` exists. 
Rollback to rc1 is fixing this, but...

![photo_2015-10-17_22-21-09](https://cloud.githubusercontent.com/assets/1761252/10560776/cf7f64b4-751d-11e5-8490-deccb5c360e5.jpg)

**Comment by samskivert** [comment]
Sorry about that, I forgot to update the error message. It needs screenSize now too:

```
                  android:configChanges="keyboardHidden|orientation|screenSize"
```

**Comment by kles4enko** [comment]
OK. It needs to fix in archetype, I created project from it.                                                                                                                                                                                                                                                                                                                                         BR,Andrey                                                                                                                                                                                                                От: Michael BayneОтправлено: нядзеля, 18 кастрычнік 2015 00.22Кому: playn/playnОтветить: playn/playnКопия: Kles4enko AndreyТема: Re: [playn] 2.0-rc2 android: Ubable to guarantee application will handle configuration change.. (#16)Sorry about that, I forgot to update the error message. It needs screenSize now too:

                  android:configChanges="keyboardHidden|orientation|screenSize"


—Reply to this email directly or view it on GitHub.

**Comment by samskivert** [comment]
Maybe you used an old archetype. It looks like the 2.0-rc2 archetype has `screenSize` in it:

https://github.com/playn/playn/blob/master/archetype/src/main/resources/archetype-resources/android/AndroidManifest.xml

**Comment by kles4enko** [comment]
‎Yep! It was rc1 archetype. Sorry                                                                                                                                                                                                                                                                                                                                         BR,Andrey‎                                                                                                                                                                                                                


  
  



‎
