### ISSUE TITLE
Can not compile android build in gradle cause 'com.google.android » apk-expansion' was removed from maven central

### ISSUE THREAD

**Issue by kles4enko** [playn/playn#42]
Hi,
I'm tying to configure gradle for playn project, instead of maven. 
I found that gradle can't resolve "apk-extention" dependency:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> Could not resolve all dependencies for configuration ':android:_debugApkCopy'.
   > Could not find com.google.android:apk-expansion:r3.
     Required by:
         project :android > io.playn:playn-android:2.0-rc3

```

If [check ](http://mvnrepository.com/artifact/com.google.android/apk-expansion)maven central for this package I see 404:
`[404] Not Found: /artifact/com.google.android/apk-expansion`

Workaround for gradle based android builds is to exclude this dependency. It works fine. But maven users must see an error.

**Comment by samskivert** [comment]
That was removed in May 2016:

```
commit da170a9cc05d1f9f9f67a3ebbab98f0b2f2dbb01
Author: Michael Bayne <mdb@fb.com>
Date:   Thu May 19 12:22:25 2016 -0700

    Remove APK expansion file support.
```

Are you using an old release or something?

**Comment by samskivert** [comment]
Oh I see that it's showing rc3, that's weird. That should definitely not have that dependency.

**Comment by samskivert** [comment]
Oh wow. rc3 was released in December 2015. Wow, I am working on geologic time here. I'll release an rc4 for now and at least sort that out.

**Comment by samskivert** [comment]
OK, I just shipped an rc4 which should not have this problem.

**Comment by kles4enko** [comment]
>>Oh wow. rc3 was released in December 2015.
Wow, I thought that it was release in June 2016...))

Many thanks!
