### ISSUE TITLE
Error Maven

### ISSUE THREAD

**Issue by avazquezdev** [playn/playn#44]
Hi, All. 
I'm new using PlayN.
1 - I have generated a sample project with the following command (mvn archetype:generate -DarchetypeGroupId=io.playn -DarchetypeArtifactId=playn-archetype -DarchetypeVersion=2.0)
The problem is that when I try to compile the project from console (mvn test -e -X) I get the following error:

[error-maven-android.txt](https://github.com/playn/playn/files/1068479/error-maven-android.txt)

Do you have any idea how I can solve it?

2 - I've also tried compiling the playn-samples in eclipse (Neon) but  it also generates an error

Plugin execution not covered by lifecycle configuration: com.simpligility.maven.plugins:android-maven-plugin:4.2.1:emma (execution: default-emma, phase: process-classes)	pom.xml	/playn-hello-android	

Versions:
maven-3.5.0
Java version: 1.8 (Oracle)

[Edit update error]

**Comment by samskivert** [comment]
This is not an issue with PlayN. Please post getting started support questions to the Google group:

https://groups.google.com/forum/#!forum/playn

**Comment by samskivert** [comment]
As for your problem, I don't know why it is attempting to compile the Android submodule. It should not. Did you modify the pom.xml after generating your project? When I generate a project and run that exact command (`mvn -e -X test'`) it compiles only the assets, core and java submodules as expected:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Test Metaproject ................................... SUCCESS [  0.352 s]
[INFO] Test Assets ........................................ SUCCESS [  0.478 s]
[INFO] Test Core .......................................... SUCCESS [  1.669 s]
[INFO] Test Java .......................................... SUCCESS [  0.323 s]
[INFO] ------------------------------------------------------------------------
```

**Comment by samskivert** [comment]
Incidentally, that is not the correct command to run. The getting started instructions say that you should run `mvn test -Pjava` not plain `mvn test`. The latter won't fail, but it won't run the game either.
