### ISSUE TITLE
Mouse click events not working for Microsoft touch screen laptops (HTML backend)

### ISSUE THREAD

**Issue by IgorBelyayev** [playn/playn#50]
Using any browser on a touch screen Microsoft laptop, mouse events are not sent to PlayN when the input device is the trackpad or a mouse. When the input device is the touchscreen, however, events are sent and received as expected.

I have observed this issue on a few different Lenovo Yoga models and believe it extends to all PCs with touch screens based on our customer bug reports.

**Comment by samskivert** [comment]
That seems surprising as PlayN just uses standard HTML5 input events. Is the game code using the `Pointer` API (which merges both touch and mouse events into a single stream) or the `Touch` or `Mouse` APIs directly?

**Comment by IgorBelyayev** [comment]
It is using the `Pointer` API.

**Comment by IgorBelyayev** [comment]
I ended up ditching `Pointer` and instead using both `Touch` and `Mouse` listeners.
