### ISSUE TITLE
Input.mouseEnabled / touchEnabled / keyboardEnabled ignored

### ISSUE THREAD

**Issue by guillerodriguez** [playn/playn#53]
playn.core.Input has a set of boolean flags (mouseEnabled, touchEnabled, keyboardEnabled) which are supposed to enable or disable dispatching of the corresponding types of events. tripleplay.game.ScreenStack actually uses this to disable dispatching of input events during transitions.

However this does not seem to work; nobody seems to be checking the state of these variables before dispatching events.

Indeed, while testing on the Java and Android backends, I see that events *are* dispatched during screen transitions, even though they should not be.

**Comment by samskivert** [comment]
Well that's a grievous oversight! I will fix.

I guess I have almost always used the Pointer code to test things, and Pointer does honor that flag.

**Comment by guillerodriguez** [comment]
This should fix it indeed, however instead of having a lot of scattered checks all around the place, wouldn't it be better to have this managed by the Input class itself ? e.g.:

        Signal<Mouse.Event> mouseEvents = new Signal<Mouse.Event>() {
        	@Override public void emit(Mouse.Event event) { if (mouseEnabled) notifyEmit(event); }
        };
        Signal<Touch.Event[]> touchEvents = new Signal<Touch.Event[]>() {
        	@Override public void emit(Touch.Event[] events) { if (touchEnabled) notifyEmit(events); }
        };
        Signal<Keyboard.Event> keyboardEvents = new Signal<Keyboard.Event>() {
        	@Override public void emit(Keyboard.Event event) { if (keyboardEnabled) notifyEmit(event); }
        };

**Comment by samskivert** [comment]
Yeah, I considered that approach as well. I was keen to take advantage of the ability to avoid creating an event object at all in cases where the relevant input source was disabled, but that was probably premature/unnecessary optimization. I'll go back and change it to use a single check when I get a chance.
