### ISSUE TITLE
JVM game crashes on start with java.lang.NoSuchMethodError: java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer

### ISSUE THREAD

**Issue by cdietze** [playn/playn#54]
```
     [java] viewPortChanged 1280x960 / 2.0 -> 640.0x480.0
     [java] Exception in thread "main" java.lang.NoSuchMethodError: java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer;
     [java] 	at playn.core.GL20$Buffers.resizeIntBuffer(GL20.java:397)
     [java] 	at playn.core.GL20.glGetShaderiv(GL20.java:631)
     [java] 	at playn.core.GLProgram.compileShader(GLProgram.java:112)
     [java] 	at playn.core.GLProgram.<init>(GLProgram.java:45)
     [java] 	at playn.core.TriangleBatch.<init>(TriangleBatch.java:122)
     [java] 	at playn.core.TriangleBatch.<init>(TriangleBatch.java:114)
     [java] 	at playn.scene.SceneGame.createDefaultBatch(SceneGame.java:95)
     [java] 	at playn.scene.SceneGame.<init>(SceneGame.java:38)
     [java] 	at rook.core.MainGame.<init>(MainGame.java:25)
     [java] 	at rook.java.JavaMain.main(JavaMain.java:13)
     [java] Java Result: 1
```
This seems to be [an issue with lwjgl which is fixed since 3.1.5](https://github.com/LWJGL/lwjgl3/issues/351#issuecomment-345814751). I locally updated lwjgl in playn to 3.1.6 and the error disappears.

**UPDATE**
just recompiling `playn` locally also makes the error disappear, so it seems to have nothing to do with lwjgl. But rather with playn being built with java 9 (as far as I can tell from the MANIFEST) and me using java 8 locally.

**Comment by cdietze** [comment]
One problem with using java 9 is that the current version of GWT used in playn (2.8.1) does not support it. [Only starting with 2.8.2. using a java 9 compiler is supported.](http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_2)

To summarize: java 8 makes jvm crash, java 9 makes html crash.

I tried bumping the GWT dependency to 2.8.2. but that causes the GWT tests to print error messages:
```
[INFO] Running playn.html.GwtTestHtmlJson
[INFO] [ERROR] jreLeakPrevention.gcDaemonFail
[INFO] java.lang.ClassNotFoundException: sun.misc.GC
...
```
the build succeeds though.

So I suppose releasing a playn version built with java 8 is the simplest way out.

**Comment by cdietze** [comment]
The stack trace from my first post is the exception that I get.

The difference seems to come from how `position(int)` is defined.
Java 9 :
```
class IntBuffer { 
public IntBuffer position​(int newPosition);
}
```

In Java 8 `IntBuffer` does not define `position` but is inherited from `Buffer`, thus has return type `Buffer`.

And that manifests in the bytecode (`java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer`).

**Comment by cdietze** [comment]
One way to deal with that seems to be to cast to `Buffer` and explicitly call `position` on that: https://stackoverflow.com/a/48694075/522998

**Comment by guillerodriguez** [comment]
@samskivert:

> Odd that building with Java 9 but targeting java 7 results in code that
crashes. I was under the impression that it was safe to build for an older
version of Java using the latest version.

Not sure how the offending code was compiled, but perhaps this is a case of a missing `-bootclasspath` option? See: https://blogs.oracle.com/darcy/how-to-cross-compile-for-older-platform-versions

In JDK 9 you can also use `-release`: http://openjdk.java.net/jeps/247

**Comment by kles4enko** [comment]
The same issue for me in PlayN 2.0.3 using java 8. If I rollback to 4.0.1 everything is OK. Looks like issue in LWJGL 3 version

**Comment by cdietze** [comment]
@kles4enko One workaround is to use the snapshots which are built by travis which uses Java8.
Set the playn.version to `2.1-SNAPSHOT` and add the snapshots repo to your pom.xml:
```
...
      <repository>
          <id>snapshots-repo</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
      </repository>
```
That's what I'm doing.

**Comment by kles4enko** [comment]
@samskivert But Java 9 is outdated/deprecated now ;) Used 10 or 8 LTS

**Comment by darthbinamira** [comment]
Sorry to revive this issue, but 11 LTS is coming end of this month I guess :)

Anyway, I'm also seeing the same issue (`Exception in thread "main" java.lang.NoSuchMethodError: java.nio.IntBuffer.position(I)Ljava/nio/IntBuffer;`) after fiddling around trying to finally get it compiling/packaging with all the required files with Bazel.

I only used LWJGL 3.1.6 btw, so it's still failing there, at least for me.

**Comment by cdietze** [comment]
Hm, my patch only addresses jdk version 9:

      <activation>
        <jdk>9</jdk>
      </activation>

I assume replacing `9` with `[9,)` makes it work for newer versions as well.

**Comment by darthbinamira** [comment]
I don't have JDK 9 installed, but instead created a PR with your suggestion above.

Also tried using the 2.1-SNAPSHOT but getting the same error.

**Comment by darthbinamira** [comment]
Just tried the latest release 2.0.4 and could no longer see the problem. 😃
