### ISSUE TITLE
Crashes on iOS12

### ISSUE THREAD

**Issue by guillerodriguez** [playn/playn#60]
There is an issue with the Boehm gc used in RoboVM which causes crashes in iOS 12. This has been fixed in RoboVM 2.3.5 (released a few days ago). More info about the issue can be found [here](https://github.com/MobiVM/robovm/issues/317). Also there is an in-depth explanation in [dkimitsa's blog](https://dkimitsa.github.io/2018/08/21/investigating-ios12-beta-crash-vol4/)

It may be a good idea to update the RoboVM dependency (currently on 2.3.3) to 2.3.5 to benefit from this fix.

**Comment by samskivert** [comment]
I updated the master POM. Just as a note: it is also trivially easy for a game project to update their RoboVM version by just adding a property to the top-level POM file for the game:

```xml
<properties>
  ...
  <robovm.version>2.3.5</robovm.version>
</properties>
```
