### ISSUE TITLE
Graphic problem after showing a video ad

### ISSUE THREAD

**Issue by beshkoon** [playn/playn#64]
I am using StartApp ads with my game. After showing a rewarded video some parts of game textures become black. I think it might be opengl context problem. how to solve it?
here is my game : https://github.com/beshkoon/beshkoon/raw/master/beshkoon.github.io/amintest-release.apk

**Comment by guillerodriguez** [comment]
Pretty difficult to help without being able to see any code.

**Comment by tulsidas** [comment]
Sounds like the same thing that happened to me, check this thread:

https://groups.google.com/forum/#!topic/playn/H6U9lXUc4rc

**Comment by guillerodriguez** [comment]
@samskivert As pointed out by @tulsidas, this is probably the same issue discussed in the linked thread. If there are no updates from @beshkoon I suggest to close this issue.
