### ISSUE TITLE
Provide 64-bit version of libplayn-android-nativelib.so

### ISSUE THREAD

**Issue by kles4enko** [playn/playn#65]
[Google recently announced](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) that future updates of the applications must include 64-bit version of native libraries.
To be honest, I don't know what libplayn-android-nativelib.so does, maybe it's something very old, but it still part of the PlayN android module.

**Comment by samskivert** [comment]
Yeah that's ancient code to support ancient versions of Android (pre-HoneyComb). I'll just remove it.

**Comment by samskivert** [comment]
Oh, I apparently did remove it in 2.0, I just forgot to remove the shared library I guess.

**Comment by kles4enko** [comment]
Thanks!
