### ISSUE TITLE
When devicePixelRatio is not 1:1, scaling happens at every drawing operation - perhaps too often

### ISSUE THREAD

**Issue by codemonkey232** [playn/playn#82]
So the devicePixelRatio and therefore platform.graphics.scale can be different on different platforms, but as far as I understand, this is mostly hidden from the dev. That is, the dev is supposed to develop for a devicePixelRatio of one - or just supposed to develop for logical pixels - and Playn will take care of scaling things for you.

Unfortunately, Playn doesn't do this in a fully transparent manner. For instance, it is very difficult to get a Canvas with Scale.ONE if you are on a platform with something other than 1:1 devicePixelRatio. This leads to the desired behavior if you manage to use exactly one Canvas to render to the screen, but if you use multiple canvases in series, then graphics can end up scaled multiple times.

More concretely, I developed a couple of games using pure java - using Graphics2D and BufferedImage. Sometimes I do multiple preprocessing steps on an image during startup or on level load before I display it. I might cut an image into smaller tiles, composite several tiles together into a larger prerendered image, create a recolored copy of an image, etc. When I ported the code to use Playn, playn.core.Image and playn.core.Canvas, this continued to work, but only on platforms with 1:1 devicePixelRatio - other platforms suffer from images being scaled each time a playn.core.Canvas is used.

It is possible on the HtmlPlatform to change some of this by messing with the config, and also the HtmlPlatform code has enough seams to be able to instantiate an HtmlCanvas of Scale.ONE without modifying Playn itself.

Unfortunately on the JavaPlatform, the config does not expose the scaleFactor (see linked closed issue below), and also it is more difficult to reliably instantiate a JavaCanvas of Scale.ONE - the JavaCanvas and similar classes are package private.

These are the only two platforms I am trying at the moment so I cannot be sure how this works on other platforms.

Possible fixes:
1. Add support for obtaining a playn.core.Canvas of a certain size with Scale.ONE - in fact, I think this is probably the correct default implementation of Graphics.createCanvas? I think in general requesting a Canvas that is the same size as a certain Image, then drawing that image on that Canvas, should result in an identical Image - the current behavior where it does not necessarily do so is surprising. In fact, I think the only place where the scaleFactor should take effect is at the last step, drawing to the the screen - so when rendering to the window's surface, and when taking input events from the window's surface. But, I might be wrong.
If it turns out this is not the correct default, then exposing something like Graphics.createCanvasImpl(scale, width, height) would also be sufficient.

2. Add support for setting the scaleFactor config on JavaPlatform / other platforms.

3. Make a few more classes public eg JavaCanvas to make it easier to override this behavior without forking Playn.

See also: https://github.com/playn/playn/issues/22#issuecomment-165283685
"I'll look into replicating this level of control on the Java and iOS backends at some point."

**Comment by samskivert** [comment]
I added support for creating a canvas with a custom scale factor, so hopefully that allows you to do what you want.

In general, creating a canvas with the device scale factor _is_ the right default. The intention is to allow most developers to think entirely in "display pixels" and never worry about device (physical) pixels. The current behavior enables that.
