### ISSUE TITLE
GWT compile-to-JS step doesn't work on Java 10

### ISSUE THREAD

**Issue by codemonkey232** [playn/playn#83]
Not sure what fixing this would involve - if GWT is still being maintained for instance. But have documented it here in case it helps anyone. Note that the error message is very cryptic, but once I understood the problem I was able to find a workaround.

$ java -version
java 10.0.1 2018-04-17

$ mvn integration-test -P html
....
[INFO] --- gwt-maven-plugin:2.7.0:compile (default) @ myproject-html ---
[INFO] Compiling module com.example.MyProject
[INFO]    **[ERROR] Hint: Check that your module inherits 'com.google.gwt.core.Core' either directly or indirectly (most often by inheriting module 'com.google.gwt.user.User')**
...
**[INFO] BUILD FAILURE**
...
[ERROR] Failed to execute goal org.codehaus.mojo:gwt-maven-plugin:2.7.0:compile (default) on project myproject-html: 

**== Failed workaround:**
There may be a workaround involving using the latest version of GWT - GWT 2.8.2 is supposed to work on Java 10. However, I don't understand the build process well enough to get this to work.

**== Actual workaround:**
Downgrading Java to 1.8 or before makes the GWT compilation step work. Note that it is not necessary to uninstall java 10, there are various ways to temporarily give an earlier version of java priority.

$ java -version
java version "1.8.0_211"

**Comment by samskivert** [comment]
I updated the default GWT version to 2.8.2. You can add:

```
<properties>
  <gwt.version>2.8.2</gwt.version>
</properties>
```

to your game's top-level `pom.xml` file to apply this upgrade to your local game until the next playn release.
